{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "99432d0a-fe6f-4e62-8fc0-f00f3e576641",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "#PATH_TO_MODEL = \"ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8\"\n",
    "\n",
    "\"\"\" Now we are going to train using SSD MOBILENET V2 Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a43d1876-c8d4-4c0f-ad69-e2c67899a021",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "# !code ./training/TF2/training/{PATH_TO_MODEL}/pipeline.config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "363af96e-8807-463d-a0f1-bb874754b60d",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"Now we are going to start training our model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "1d477710-40be-4135-b726-0842c3a01f11",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow_addons\\utils\\tfa_eol_msg.py:23: UserWarning: \n",
      "\n",
      "TensorFlow Addons (TFA) has ended development and introduction of new features.\n",
      "TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.\n",
      "Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). \n",
      "\n",
      "For more information see: https://github.com/tensorflow/addons/issues/2807 \n",
      "\n",
      "  warnings.warn(\n",
      "INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)\n",
      "I0104 17:52:59.334078  1788 mirrored_strategy.py:374] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)\n",
      "INFO:tensorflow:Maybe overwriting train_steps: 6000\n",
      "I0104 17:52:59.338286  1788 config_util.py:552] Maybe overwriting train_steps: 6000\n",
      "INFO:tensorflow:Maybe overwriting use_bfloat16: False\n",
      "I0104 17:52:59.338286  1788 config_util.py:552] Maybe overwriting use_bfloat16: False\n",
      "WARNING:tensorflow:From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\object_detection\\model_lib_v2.py:545: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "rename to distribute_datasets_from_function\n",
      "W0104 17:52:59.357249  1788 deprecation.py:350] From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\object_detection\\model_lib_v2.py:545: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "rename to distribute_datasets_from_function\n",
      "INFO:tensorflow:Reading unweighted datasets: ['data/train.record']\n",
      "I0104 17:52:59.361801  1788 dataset_builder.py:163] Reading unweighted datasets: ['data/train.record']\n",
      "INFO:tensorflow:Reading record datasets for input file: ['data/train.record']\n",
      "I0104 17:52:59.361801  1788 dataset_builder.py:80] Reading record datasets for input file: ['data/train.record']\n",
      "INFO:tensorflow:Number of filenames to read: 1\n",
      "I0104 17:52:59.361801  1788 dataset_builder.py:81] Number of filenames to read: 1\n",
      "WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.\n",
      "W0104 17:52:59.362802  1788 dataset_builder.py:87] num_readers has been reduced to 1 to match input file shards.\n",
      "WARNING:tensorflow:From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\object_detection\\builders\\dataset_builder.py:101: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.deterministic`.\n",
      "W0104 17:52:59.366791  1788 deprecation.py:350] From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\object_detection\\builders\\dataset_builder.py:101: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.deterministic`.\n",
      "WARNING:tensorflow:From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\object_detection\\builders\\dataset_builder.py:236: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.data.Dataset.map()\n",
      "W0104 17:52:59.377762  1788 deprecation.py:350] From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\object_detection\\builders\\dataset_builder.py:236: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.data.Dataset.map()\n",
      "WARNING:tensorflow:From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:1176: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.\n",
      "W0104 17:53:04.072938  1788 deprecation.py:350] From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:1176: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.\n",
      "WARNING:tensorflow:From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:1176: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.\n",
      "W0104 17:53:06.215496  1788 deprecation.py:350] From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:1176: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.\n",
      "WARNING:tensorflow:From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:1176: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.cast` instead.\n",
      "W0104 17:53:07.495526  1788 deprecation.py:350] From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:1176: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.cast` instead.\n",
      "C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\keras\\backend.py:451: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.\n",
      "  warnings.warn(\n",
      "WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "W0104 17:53:41.779860  1788 checkpoint.py:204] Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._box_prediction_head._box_encoder_layers.0.depthwise_kernel\n",
      "W0104 17:53:41.779860  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._box_prediction_head._box_encoder_layers.0.depthwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._box_prediction_head._box_encoder_layers.0.pointwise_kernel\n",
      "W0104 17:53:41.779860  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._box_prediction_head._box_encoder_layers.0.pointwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._box_prediction_head._box_encoder_layers.0.bias\n",
      "W0104 17:53:41.779860  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._box_prediction_head._box_encoder_layers.0.bias\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.0.depthwise_kernel\n",
      "W0104 17:53:41.779860  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.0.depthwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.0.pointwise_kernel\n",
      "W0104 17:53:41.779860  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.0.pointwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.1.depthwise_kernel\n",
      "W0104 17:53:41.779860  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.1.depthwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.1.pointwise_kernel\n",
      "W0104 17:53:41.779860  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.1.pointwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.2.depthwise_kernel\n",
      "W0104 17:53:41.779860  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.2.depthwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.2.pointwise_kernel\n",
      "W0104 17:53:41.779860  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.2.pointwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.3.depthwise_kernel\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.3.depthwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.3.pointwise_kernel\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._head_scope_conv_layers.PredictionTower.3.pointwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._prediction_heads.class_predictions_with_background._class_predictor_layers.0.depthwise_kernel\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._prediction_heads.class_predictions_with_background._class_predictor_layers.0.depthwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._prediction_heads.class_predictions_with_background._class_predictor_layers.0.pointwise_kernel\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._prediction_heads.class_predictions_with_background._class_predictor_layers.0.pointwise_kernel\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._prediction_heads.class_predictions_with_background._class_predictor_layers.0.bias\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._prediction_heads.class_predictions_with_background._class_predictor_layers.0.bias\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.1.gamma\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.1.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.1.beta\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.1.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.1.moving_mean\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.1.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.1.moving_variance\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.1.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.4.gamma\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.4.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.4.beta\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.4.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.4.moving_mean\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.4.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.4.moving_variance\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.4.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.7.gamma\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.7.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.7.beta\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.7.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.7.moving_mean\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.7.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.7.moving_variance\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.7.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.10.gamma\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.10.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.10.beta\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.10.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.10.moving_mean\n",
      "W0104 17:53:41.780857  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.10.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.10.moving_variance\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.0.10.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.1.gamma\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.1.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.1.beta\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.1.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.1.moving_mean\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.1.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.1.moving_variance\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.1.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.4.gamma\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.4.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.4.beta\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.4.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.4.moving_mean\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.4.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.4.moving_variance\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.4.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.7.gamma\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.7.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.7.beta\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.7.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.7.moving_mean\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.7.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.7.moving_variance\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.7.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.10.gamma\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.10.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.10.beta\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.10.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.10.moving_mean\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.10.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.10.moving_variance\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.1.10.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.1.gamma\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.1.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.1.beta\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.1.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.1.moving_mean\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.1.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.1.moving_variance\n",
      "W0104 17:53:41.781854  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.1.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.4.gamma\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.4.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.4.beta\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.4.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.4.moving_mean\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.4.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.4.moving_variance\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.4.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.7.gamma\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.7.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.7.beta\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.7.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.7.moving_mean\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.7.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.7.moving_variance\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.7.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.10.gamma\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.10.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.10.beta\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.10.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.10.moving_mean\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.10.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.10.moving_variance\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.2.10.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.1.gamma\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.1.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.1.beta\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.1.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.1.moving_mean\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.1.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.1.moving_variance\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.1.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.4.gamma\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.4.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.4.beta\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.4.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.4.moving_mean\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.4.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.4.moving_variance\n",
      "W0104 17:53:41.782852  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.4.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.7.gamma\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.7.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.7.beta\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.7.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.7.moving_mean\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.7.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.7.moving_variance\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.7.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.10.gamma\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.10.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.10.beta\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.10.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.10.moving_mean\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.10.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.10.moving_variance\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.3.10.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.1.gamma\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.1.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.1.beta\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.1.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.1.moving_mean\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.1.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.1.moving_variance\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.1.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.4.gamma\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.4.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.4.beta\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.4.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.4.moving_mean\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.4.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.4.moving_variance\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.4.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.7.gamma\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.7.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.7.beta\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.7.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.7.moving_mean\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.7.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.7.moving_variance\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.7.moving_variance\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.10.gamma\n",
      "W0104 17:53:41.783850  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.10.gamma\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.10.beta\n",
      "W0104 17:53:41.784848  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.10.beta\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.10.moving_mean\n",
      "W0104 17:53:41.784848  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.10.moving_mean\n",
      "WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.10.moving_variance\n",
      "W0104 17:53:41.784848  1788 checkpoint.py:213] Value in checkpoint could not be found in the restored object: (root).model._box_predictor._base_tower_layers_for_heads.box_encodings.4.10.moving_variance\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "I0104 17:53:42.137258  1788 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "I0104 17:53:42.139494  1788 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "I0104 17:53:42.141993  1788 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "I0104 17:53:42.142458  1788 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "I0104 17:53:42.144483  1788 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "I0104 17:53:42.145452  1788 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "I0104 17:53:42.146478  1788 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "I0104 17:53:42.148011  1788 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "I0104 17:53:42.150035  1788 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "I0104 17:53:42.151038  1788 cross_device_ops.py:616] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "WARNING:tensorflow:From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py:629: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use fn_output_signature instead\n",
      "W0104 17:53:47.964614  4040 deprecation.py:554] From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py:629: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use fn_output_signature instead\n",
      "INFO:tensorflow:Step 100 per-step time 0.492s loss=0.703\n",
      "I0104 17:54:48.970453  1788 model_lib_v2.py:679] Step 100 per-step time 0.492s loss=0.703\n",
      "INFO:tensorflow:Step 200 per-step time 0.498s loss=0.654\n",
      "I0104 17:55:38.564639  1788 model_lib_v2.py:679] Step 200 per-step time 0.498s loss=0.654\n",
      "INFO:tensorflow:Step 300 per-step time 0.481s loss=0.540\n",
      "I0104 17:56:27.515548  1788 model_lib_v2.py:679] Step 300 per-step time 0.481s loss=0.540\n",
      "INFO:tensorflow:Step 400 per-step time 0.472s loss=0.544\n",
      "I0104 17:57:16.600873  1788 model_lib_v2.py:679] Step 400 per-step time 0.472s loss=0.544\n",
      "INFO:tensorflow:Step 500 per-step time 0.510s loss=0.453\n",
      "I0104 17:58:06.248962  1788 model_lib_v2.py:679] Step 500 per-step time 0.510s loss=0.453\n",
      "INFO:tensorflow:Step 600 per-step time 0.487s loss=0.461\n",
      "I0104 17:58:55.549436  1788 model_lib_v2.py:679] Step 600 per-step time 0.487s loss=0.461\n",
      "INFO:tensorflow:Step 700 per-step time 0.497s loss=0.518\n",
      "I0104 17:59:44.844106  1788 model_lib_v2.py:679] Step 700 per-step time 0.497s loss=0.518\n",
      "INFO:tensorflow:Step 800 per-step time 0.486s loss=0.416\n",
      "I0104 18:00:34.306530  1788 model_lib_v2.py:679] Step 800 per-step time 0.486s loss=0.416\n",
      "INFO:tensorflow:Step 900 per-step time 0.494s loss=0.468\n",
      "I0104 18:01:24.027917  1788 model_lib_v2.py:679] Step 900 per-step time 0.494s loss=0.468\n",
      "INFO:tensorflow:Step 1000 per-step time 0.508s loss=0.491\n",
      "I0104 18:02:13.488655  1788 model_lib_v2.py:679] Step 1000 per-step time 0.508s loss=0.491\n",
      "INFO:tensorflow:Step 1100 per-step time 0.481s loss=0.381\n",
      "I0104 18:03:03.469363  1788 model_lib_v2.py:679] Step 1100 per-step time 0.481s loss=0.381\n",
      "INFO:tensorflow:Step 1200 per-step time 0.519s loss=0.454\n",
      "I0104 18:03:53.106685  1788 model_lib_v2.py:679] Step 1200 per-step time 0.519s loss=0.454\n",
      "INFO:tensorflow:Step 1300 per-step time 0.521s loss=0.348\n",
      "I0104 18:04:42.947640  1788 model_lib_v2.py:679] Step 1300 per-step time 0.521s loss=0.348\n",
      "INFO:tensorflow:Step 1400 per-step time 0.479s loss=0.372\n",
      "I0104 18:05:32.786591  1788 model_lib_v2.py:679] Step 1400 per-step time 0.479s loss=0.372\n",
      "INFO:tensorflow:Step 1500 per-step time 0.474s loss=0.360\n",
      "I0104 18:06:22.056518  1788 model_lib_v2.py:679] Step 1500 per-step time 0.474s loss=0.360\n",
      "INFO:tensorflow:Step 1600 per-step time 0.493s loss=0.360\n",
      "I0104 18:07:11.346182  1788 model_lib_v2.py:679] Step 1600 per-step time 0.493s loss=0.360\n",
      "INFO:tensorflow:Step 1700 per-step time 0.516s loss=0.309\n",
      "I0104 18:08:01.566350  1788 model_lib_v2.py:679] Step 1700 per-step time 0.516s loss=0.309\n",
      "INFO:tensorflow:Step 1800 per-step time 0.493s loss=0.363\n",
      "I0104 18:08:51.402247  1788 model_lib_v2.py:679] Step 1800 per-step time 0.493s loss=0.363\n",
      "INFO:tensorflow:Step 1900 per-step time 0.483s loss=0.344\n",
      "I0104 18:09:40.916935  1788 model_lib_v2.py:679] Step 1900 per-step time 0.483s loss=0.344\n",
      "INFO:tensorflow:Step 2000 per-step time 0.514s loss=0.339\n",
      "I0104 18:10:30.636321  1788 model_lib_v2.py:679] Step 2000 per-step time 0.514s loss=0.339\n",
      "INFO:tensorflow:Step 2100 per-step time 0.456s loss=0.380\n",
      "I0104 18:11:20.770281  1788 model_lib_v2.py:679] Step 2100 per-step time 0.456s loss=0.380\n",
      "INFO:tensorflow:Step 2200 per-step time 0.476s loss=0.294\n",
      "I0104 18:12:10.950999  1788 model_lib_v2.py:679] Step 2200 per-step time 0.476s loss=0.294\n",
      "INFO:tensorflow:Step 2300 per-step time 0.495s loss=0.302\n",
      "I0104 18:13:01.428070  1788 model_lib_v2.py:679] Step 2300 per-step time 0.495s loss=0.302\n",
      "INFO:tensorflow:Step 2400 per-step time 0.530s loss=0.311\n",
      "I0104 18:13:50.869352  1788 model_lib_v2.py:679] Step 2400 per-step time 0.530s loss=0.311\n",
      "INFO:tensorflow:Step 2500 per-step time 0.524s loss=0.310\n",
      "I0104 18:14:40.687987  1788 model_lib_v2.py:679] Step 2500 per-step time 0.524s loss=0.310\n",
      "INFO:tensorflow:Step 2600 per-step time 0.480s loss=0.337\n",
      "I0104 18:15:30.139189  1788 model_lib_v2.py:679] Step 2600 per-step time 0.480s loss=0.337\n",
      "INFO:tensorflow:Step 2700 per-step time 0.516s loss=0.281\n",
      "I0104 18:16:19.465392  1788 model_lib_v2.py:679] Step 2700 per-step time 0.516s loss=0.281\n",
      "INFO:tensorflow:Step 2800 per-step time 0.516s loss=0.260\n",
      "I0104 18:17:09.138315  1788 model_lib_v2.py:679] Step 2800 per-step time 0.516s loss=0.260\n",
      "INFO:tensorflow:Step 2900 per-step time 0.502s loss=0.321\n",
      "I0104 18:17:58.763790  1788 model_lib_v2.py:679] Step 2900 per-step time 0.502s loss=0.321\n",
      "INFO:tensorflow:Step 3000 per-step time 0.489s loss=0.278\n",
      "I0104 18:18:48.608469  1788 model_lib_v2.py:679] Step 3000 per-step time 0.489s loss=0.278\n",
      "INFO:tensorflow:Step 3100 per-step time 0.496s loss=0.380\n",
      "I0104 18:19:38.980127  1788 model_lib_v2.py:679] Step 3100 per-step time 0.496s loss=0.380\n",
      "INFO:tensorflow:Step 3200 per-step time 0.484s loss=0.282\n",
      "I0104 18:20:28.416766  1788 model_lib_v2.py:679] Step 3200 per-step time 0.484s loss=0.282\n",
      "INFO:tensorflow:Step 3300 per-step time 0.533s loss=0.276\n",
      "I0104 18:21:17.779618  1788 model_lib_v2.py:679] Step 3300 per-step time 0.533s loss=0.276\n",
      "INFO:tensorflow:Step 3400 per-step time 0.510s loss=0.329\n",
      "I0104 18:22:07.193532  1788 model_lib_v2.py:679] Step 3400 per-step time 0.510s loss=0.329\n",
      "INFO:tensorflow:Step 3500 per-step time 0.485s loss=0.279\n",
      "I0104 18:22:56.649872  1788 model_lib_v2.py:679] Step 3500 per-step time 0.485s loss=0.279\n",
      "INFO:tensorflow:Step 3600 per-step time 0.499s loss=0.271\n",
      "I0104 18:23:46.307455  1788 model_lib_v2.py:679] Step 3600 per-step time 0.499s loss=0.271\n",
      "INFO:tensorflow:Step 3700 per-step time 0.474s loss=0.332\n",
      "I0104 18:24:35.827346  1788 model_lib_v2.py:679] Step 3700 per-step time 0.474s loss=0.332\n",
      "INFO:tensorflow:Step 3800 per-step time 0.467s loss=0.292\n",
      "I0104 18:25:25.318968  1788 model_lib_v2.py:679] Step 3800 per-step time 0.467s loss=0.292\n",
      "INFO:tensorflow:Step 3900 per-step time 0.505s loss=0.229\n",
      "I0104 18:26:14.784550  1788 model_lib_v2.py:679] Step 3900 per-step time 0.505s loss=0.229\n",
      "INFO:tensorflow:Step 4000 per-step time 0.494s loss=0.241\n",
      "I0104 18:27:04.137495  1788 model_lib_v2.py:679] Step 4000 per-step time 0.494s loss=0.241\n",
      "INFO:tensorflow:Step 4100 per-step time 0.471s loss=0.292\n",
      "I0104 18:27:53.902357  1788 model_lib_v2.py:679] Step 4100 per-step time 0.471s loss=0.292\n",
      "INFO:tensorflow:Step 4200 per-step time 0.517s loss=0.232\n",
      "I0104 18:28:43.281789  1788 model_lib_v2.py:679] Step 4200 per-step time 0.517s loss=0.232\n",
      "INFO:tensorflow:Step 4300 per-step time 0.486s loss=0.227\n",
      "I0104 18:29:32.745911  1788 model_lib_v2.py:679] Step 4300 per-step time 0.486s loss=0.227\n",
      "INFO:tensorflow:Step 4400 per-step time 0.478s loss=0.229\n",
      "I0104 18:30:21.971958  1788 model_lib_v2.py:679] Step 4400 per-step time 0.478s loss=0.229\n",
      "INFO:tensorflow:Step 4500 per-step time 0.509s loss=0.247\n",
      "I0104 18:31:11.360305  1788 model_lib_v2.py:679] Step 4500 per-step time 0.509s loss=0.247\n",
      "INFO:tensorflow:Step 4600 per-step time 0.495s loss=0.269\n",
      "I0104 18:32:00.927144  1788 model_lib_v2.py:679] Step 4600 per-step time 0.495s loss=0.269\n",
      "INFO:tensorflow:Step 4700 per-step time 0.494s loss=0.256\n",
      "I0104 18:32:50.470165  1788 model_lib_v2.py:679] Step 4700 per-step time 0.494s loss=0.256\n",
      "INFO:tensorflow:Step 4800 per-step time 0.503s loss=0.234\n",
      "I0104 18:33:39.770639  1788 model_lib_v2.py:679] Step 4800 per-step time 0.503s loss=0.234\n",
      "INFO:tensorflow:Step 4900 per-step time 0.485s loss=0.315\n",
      "I0104 18:34:29.239034  1788 model_lib_v2.py:679] Step 4900 per-step time 0.485s loss=0.315\n",
      "INFO:tensorflow:Step 5000 per-step time 0.496s loss=0.267\n",
      "I0104 18:35:19.030151  1788 model_lib_v2.py:679] Step 5000 per-step time 0.496s loss=0.267\n",
      "INFO:tensorflow:Step 5100 per-step time 0.492s loss=0.298\n",
      "I0104 18:36:08.835143  1788 model_lib_v2.py:679] Step 5100 per-step time 0.492s loss=0.298\n",
      "INFO:tensorflow:Step 5200 per-step time 0.496s loss=0.228\n",
      "I0104 18:36:58.135845  1788 model_lib_v2.py:679] Step 5200 per-step time 0.496s loss=0.228\n",
      "INFO:tensorflow:Step 5300 per-step time 0.491s loss=0.270\n",
      "I0104 18:37:47.410162  1788 model_lib_v2.py:679] Step 5300 per-step time 0.491s loss=0.270\n",
      "INFO:tensorflow:Step 5400 per-step time 0.503s loss=0.240\n",
      "I0104 18:38:36.832989  1788 model_lib_v2.py:679] Step 5400 per-step time 0.503s loss=0.240\n",
      "INFO:tensorflow:Step 5500 per-step time 0.493s loss=0.275\n",
      "I0104 18:39:26.139249  1788 model_lib_v2.py:679] Step 5500 per-step time 0.493s loss=0.275\n",
      "INFO:tensorflow:Step 5600 per-step time 0.493s loss=0.247\n",
      "I0104 18:40:15.777294  1788 model_lib_v2.py:679] Step 5600 per-step time 0.493s loss=0.247\n",
      "INFO:tensorflow:Step 5700 per-step time 0.513s loss=0.208\n",
      "I0104 18:41:05.181479  1788 model_lib_v2.py:679] Step 5700 per-step time 0.513s loss=0.208\n",
      "INFO:tensorflow:Step 5800 per-step time 0.529s loss=0.242\n",
      "I0104 18:41:54.625889  1788 model_lib_v2.py:679] Step 5800 per-step time 0.529s loss=0.242\n",
      "INFO:tensorflow:Step 5900 per-step time 0.499s loss=0.236\n",
      "I0104 18:42:44.044646  1788 model_lib_v2.py:679] Step 5900 per-step time 0.499s loss=0.236\n",
      "INFO:tensorflow:Step 6000 per-step time 0.495s loss=0.235\n",
      "I0104 18:43:33.582069  1788 model_lib_v2.py:679] Step 6000 per-step time 0.495s loss=0.235\n"
     ]
    }
   ],
   "source": [
    "#!python model_main_tf2.py --model_dir=training/TF2/training/{PATH_TO_MODEL} --pipeline_config_path=training/TF2/training/{PATH_TO_MODEL}/pipeline.config --num_train_steps=6000 --alsologtostderr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5713212e-04b1-44be-b949-650a3e7a16d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\" We have completed our training with minimal loss"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a79fd598-37c4-4cef-afa1-5283b87b1336",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\autograph\\impl\\api.py:458: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with back_prop=False is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "back_prop=False is deprecated. Consider using tf.stop_gradient instead.\n",
      "Instead of:\n",
      "results = tf.map_fn(fn, elems, back_prop=False)\n",
      "Use:\n",
      "results = tf.nest.map_structure(tf.stop_gradient, tf.map_fn(fn, elems))\n",
      "W0104 19:49:39.356067 14132 deprecation.py:623] From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\autograph\\impl\\api.py:458: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with back_prop=False is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "back_prop=False is deprecated. Consider using tf.stop_gradient instead.\n",
      "Instead of:\n",
      "results = tf.map_fn(fn, elems, back_prop=False)\n",
      "Use:\n",
      "results = tf.nest.map_structure(tf.stop_gradient, tf.map_fn(fn, elems))\n",
      "WARNING:tensorflow:From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py:629: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use fn_output_signature instead\n",
      "W0104 19:49:39.356122 14132 deprecation.py:554] From C:\\Users\\MSC1\\anaconda3\\envs\\OD\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py:629: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use fn_output_signature instead\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.meta_architectures.ssd_meta_arch.SSDMetaArch object at 0x0000016D9257BC40>, because it is not built.\n",
      "W0104 19:49:54.230358 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.meta_architectures.ssd_meta_arch.SSDMetaArch object at 0x0000016D9257BC40>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.convolutional.separable_conv2d.SeparableConv2D object at 0x0000016DDB4B0730>, because it is not built.\n",
      "W0104 19:49:54.416060 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.convolutional.separable_conv2d.SeparableConv2D object at 0x0000016DDB4B0730>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB516FA0>, because it is not built.\n",
      "W0104 19:49:54.416060 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB516FA0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB5168E0>, because it is not built.\n",
      "W0104 19:49:54.416060 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB5168E0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.convolutional.separable_conv2d.SeparableConv2D object at 0x0000016DDB4E86A0>, because it is not built.\n",
      "W0104 19:49:54.416060 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.convolutional.separable_conv2d.SeparableConv2D object at 0x0000016DDB4E86A0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB4E8700>, because it is not built.\n",
      "W0104 19:49:54.416060 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB4E8700>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB4E84F0>, because it is not built.\n",
      "W0104 19:49:54.416060 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB4E84F0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.convolutional.separable_conv2d.SeparableConv2D object at 0x0000016DDB4E89D0>, because it is not built.\n",
      "W0104 19:49:54.416060 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.convolutional.separable_conv2d.SeparableConv2D object at 0x0000016DDB4E89D0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB4E80A0>, because it is not built.\n",
      "W0104 19:49:54.416060 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB4E80A0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB4EAAF0>, because it is not built.\n",
      "W0104 19:49:54.416060 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB4EAAF0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.convolutional.separable_conv2d.SeparableConv2D object at 0x0000016DDB4EA460>, because it is not built.\n",
      "W0104 19:49:54.416060 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.convolutional.separable_conv2d.SeparableConv2D object at 0x0000016DDB4EA460>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB4EA4F0>, because it is not built.\n",
      "W0104 19:49:54.416060 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB4EA4F0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB4EAEB0>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB4EAEB0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB49EBE0>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB49EBE0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB4F5D30>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB4F5D30>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB54D0A0>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB54D0A0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB54D100>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB54D100>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB58A7F0>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB58A7F0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB58A550>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB58A550>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB58AF40>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB58AF40>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB58AD90>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB58AD90>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB4674C0>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB4674C0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB50A5B0>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB50A5B0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB46EC40>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB46EC40>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB46E550>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB46E550>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB475FA0>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB475FA0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB475730>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB475730>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DAF961100>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DAF961100>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DAF9611F0>, because it is not built.\n",
      "W0104 19:49:54.417057 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DAF9611F0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB488430>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB488430>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB4CB0A0>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB4CB0A0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB51F8B0>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB51F8B0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB51F1F0>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB51F1F0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB51F8E0>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB51F8E0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB51FC40>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB51FC40>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB51F040>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB51F040>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB51F610>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB51F610>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB601D00>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB601D00>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB601D60>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB601D60>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB6065B0>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB6065B0>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB606520>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB606520>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB606A90>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB606A90>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB606A00>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB606A00>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB606F70>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <object_detection.core.freezable_batch_norm.FreezableBatchNorm object at 0x0000016DDB606F70>, because it is not built.\n",
      "WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB606EE0>, because it is not built.\n",
      "W0104 19:49:54.418055 14132 save_impl.py:66] Skipping full serialization of Keras layer <keras.layers.core.lambda_layer.Lambda object at 0x0000016DDB606EE0>, because it is not built.\n",
      "W0104 19:50:05.978262 14132 save.py:269] Found untraced functions such as WeightSharedConvolutionalBoxPredictor_layer_call_fn, WeightSharedConvolutionalBoxPredictor_layer_call_and_return_conditional_losses, WeightSharedConvolutionalBoxHead_layer_call_fn, WeightSharedConvolutionalBoxHead_layer_call_and_return_conditional_losses, WeightSharedConvolutionalClassHead_layer_call_fn while saving (showing 5 of 173). These functions will not be directly callable after loading.\n",
      "INFO:tensorflow:Assets written to: /training/TF2/training/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8/saved_model/saved_model\\assets\n",
      "I0104 19:50:10.496078 14132 builder_impl.py:779] Assets written to: /training/TF2/training/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8/saved_model/saved_model\\assets\n",
      "INFO:tensorflow:Writing pipeline config file to /training/TF2/training/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8/saved_model/pipeline.config\n",
      "I0104 19:50:11.174135 14132 config_util.py:253] Writing pipeline config file to /training/TF2/training/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8/saved_model/pipeline.config\n"
     ]
    }
   ],
   "source": [
    "#!python exporter_main_v2.py --input_type image_tensor --pipeline_config_path training/TF2/training/{PATH_TO_MODEL}/pipeline.config --trained_checkpoint_dir training/TF2/training/{PATH_TO_MODEL}/ --output_directory /training/TF2/training/{PATH_TO_MODEL}/saved_model/\n",
    "\"\"\"running evaluation script"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "808606d4-771f-466f-8434-5ac41849e203",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "It was found that lower batch size increases time for training and higher batch size increases computational \n",
    "requirements.\n",
    "Hence, batch size should be determined considering GPU memory and the higher the number of epochs,\n",
    "loss can be reduced but epochs must not be too high to avoid overfitting and higher training time. \n",
    "I used 6000 as my number of steps(epochs).\n",
    "I used batch size of 16 which was optimal for ssd mobilenet v2."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
